import { NextResponse } from 'next/server'
import { createClient as createServiceClient } from '@supabase/supabase-js'

export async function POST() {
    const sb = createServiceClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.SUPABASE_SERVICE_ROLE_KEY!
    )

    const products = [
        {
            name: 'Gold Tier Celebration Cake',
            category: 'Celebration Cakes',
            price: 65.00,
            description: 'A stunning handcrafted celebration cake made fresh to your exact specifications. Perfect for birthdays, weddings, engagements and all special occasions.',
            ingredients: 'Flour, butter, eggs, sugar, vanilla extract, milk, baking powder. Filled with your choice of buttercream, ganache or cream cheese frosting.',
            allergens: 'Gluten, Dairy, Eggs. May contain nuts. Contact us for allergen-free options.',
            serves: '10–15 people',
            notice: '5 days notice required',
            badge: 'BEST SELLER',
            is_available: true,
            is_featured: true,
            sort_order: 1,
            image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&q=80&w=600',
            options: JSON.stringify(['1 Tier', '2 Tier', '3 Tier', '4 Tier']),
            flavours: JSON.stringify(['Vanilla', 'Chocolate', 'Red Velvet', 'Lemon', 'Carrot', 'Marble']),
        },
        {
            name: 'Small Chops Platter (30 pcs)',
            category: 'Small Chops',
            price: 35.00,
            description: 'A beautifully presented mixed platter of Nigerian small chops — the life of every party. Includes puff puff, spring rolls, samosa and fish rolls.',
            ingredients: 'Puff puff: flour, yeast, sugar, nutmeg, oil. Spring rolls: pastry, minced meat, vegetables. Samosa: pastry, spiced potatoes/meat. Fish rolls: pastry, fish filling.',
            allergens: 'Gluten, Eggs, Fish. May contain dairy. Fully customisable — ask us about allergen-free options.',
            serves: '8–12 people as starter',
            notice: '48 hours notice required',
            badge: 'SIGNATURE',
            is_available: true,
            is_featured: true,
            sort_order: 2,
            image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=600',
            options: JSON.stringify(['30 pieces', '50 pieces', '80 pieces', '100 pieces']),
            flavours: JSON.stringify([]),
        },
        {
            name: 'Puff Puff Dozen',
            category: 'Puff Puff',
            price: 6.00,
            description: 'Soft, golden, perfectly spiced Nigerian puff puff made fresh daily. Our customers call them life-changing! Light, fluffy and utterly irresistible.',
            ingredients: 'Plain flour, active dry yeast, sugar, nutmeg, cinnamon, warm water, vegetable oil for frying.',
            allergens: 'Gluten. Fried in vegetable oil. No dairy, no eggs, no nuts.',
            serves: '2–3 people',
            notice: '24 hours notice',
            badge: 'MUST TRY',
            is_available: true,
            is_featured: true,
            sort_order: 3,
            image_url: 'https://images.unsplash.com/photo-1618897996318-5a901fa0807c?auto=format&fit=crop&q=80&w=600',
            options: JSON.stringify(['12 pieces', '24 pieces', '36 pieces', '50 pieces']),
            flavours: JSON.stringify(['Original', 'Coconut', 'Cinnamon Sugar', 'Spiced']),
        },
        {
            name: 'Classic Chin Chin 500g',
            category: 'Chin Chin & Snacks',
            price: 8.50,
            description: 'Traditional Nigerian chin chin — crunchy, sweet and completely addictive. Made with a treasured family recipe. Perfect for snacking, gifting and events.',
            ingredients: 'Plain flour, butter, sugar, eggs, milk, vanilla extract, nutmeg, vegetable oil for frying.',
            allergens: 'Gluten, Dairy, Eggs. No nuts.',
            serves: '4–6 people as snack',
            notice: '24 hours notice',
            badge: 'TRADITIONAL',
            is_available: true,
            is_featured: false,
            sort_order: 4,
            image_url: 'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?auto=format&fit=crop&q=80&w=600',
            options: JSON.stringify(['500g', '1kg', '2kg']),
            flavours: JSON.stringify(['Sweet', 'Coconut', 'Spiced', 'Peanut']),
        },
        {
            name: 'Nigerian Meat Pie',
            category: 'Savoury Bakes',
            price: 3.50,
            description: 'Classic Nigerian meat pie with a golden, flaky pastry crust and a hearty, well-seasoned minced meat and potato filling. Baked fresh every day.',
            ingredients: 'Shortcrust pastry: flour, butter, egg, salt. Filling: minced beef, diced potatoes, onions, carrots, thyme, curry powder, seasoning cubes.',
            allergens: 'Gluten, Dairy, Eggs. Contains beef. No nuts.',
            serves: '1 person',
            notice: '24 hours notice',
            badge: 'FRESH DAILY',
            is_available: true,
            is_featured: false,
            sort_order: 5,
            image_url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&q=80&w=600',
            options: JSON.stringify(['1 piece', '4 pieces', '8 pieces', '12 pieces']),
            flavours: JSON.stringify(['Beef & Potato', 'Chicken', 'Vegetable']),
        },
        {
            name: 'Premium Party Box',
            category: 'Party Boxes',
            price: 85.00,
            description: 'Our most popular event package — a luxury assortment of Nigerian pastries and small chops, beautifully presented in a premium gift box. Perfect for birthdays, namings and corporate events.',
            ingredients: 'Includes: puff puff, chin chin, spring rolls, samosa, meat pies and seasonal treats. Full ingredient list provided on request.',
            allergens: 'Contains Gluten, Dairy, Eggs, Fish. Full allergen breakdown available on request.',
            serves: '20–25 people',
            notice: '5 days notice required',
            badge: 'PREMIUM',
            is_available: true,
            is_featured: true,
            sort_order: 6,
            image_url: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&q=80&w=600',
            options: JSON.stringify(['Standard (20 people)', 'Large (35 people)', 'XL (50 people)']),
            flavours: JSON.stringify([]),
        },
        {
            name: 'Fish Roll',
            category: 'Savoury Bakes',
            price: 2.50,
            description: 'Golden deep-fried pastry rolls filled with a lightly spiced fish filling. A Nigerian street food classic, elevated with premium ingredients.',
            ingredients: 'Pastry: flour, butter, baking powder. Filling: tuna or mackerel, onions, peppers, seasoning.',
            allergens: 'Gluten, Fish, Dairy. No eggs, no nuts.',
            serves: '1 person',
            notice: '24 hours notice',
            badge: 'CLASSIC',
            is_available: true,
            is_featured: false,
            sort_order: 7,
            image_url: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&q=80&w=600',
            options: JSON.stringify(['1 piece', '6 pieces', '12 pieces']),
            flavours: JSON.stringify(['Tuna', 'Mackerel', 'Sardine']),
        },
        {
            name: 'Coconut Cake',
            category: 'Celebration Cakes',
            price: 45.00,
            description: 'A beautifully moist coconut sponge cake layered with coconut cream filling and finished with toasted coconut flakes. A tropical treat loved by all.',
            ingredients: 'Desiccated coconut, flour, eggs, butter, sugar, coconut milk, vanilla, coconut cream frosting.',
            allergens: 'Gluten, Dairy, Eggs. Contains coconut (tree nut). No peanuts.',
            serves: '8–10 people',
            notice: '3 days notice',
            badge: 'POPULAR',
            is_available: true,
            is_featured: false,
            sort_order: 8,
            image_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&q=80&w=600',
            options: JSON.stringify(['6 inch', '8 inch', '10 inch']),
            flavours: JSON.stringify(['Classic Coconut', 'Coconut & Lime', 'Coconut & Pineapple']),
        },
    ]

    const { error } = await sb.from('products').upsert(products, { onConflict: 'name' })

    if (error) {
        return NextResponse.json({ error: error.message }, { status: 500 })
    }

    return NextResponse.json({ success: true, count: products.length })
}
